# Generated by Django 3.2.13 on 2022-08-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetychecklistquestion',
            name='created_by',
        ),
    ]
