# Generated by Django 3.2.13 on 2022-08-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_safetychecklistquestion_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='gross_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='loading',
            name='net_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='loading',
            name='tare_weight',
            field=models.FloatField(null=True),
        ),
    ]
