# Generated by Django 3.2.13 on 2022-07-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20220718_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdriver',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='coid',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='productid',
            new_name='product',
        ),
    ]
