# Generated by Django 3.2.13 on 2022-07-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20220718_0914'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customertruck',
            constraint=models.UniqueConstraint(fields=('customer', 'truck'), name='unique_customer_truck'),
        ),
    ]
