# Generated by Django 3.2.13 on 2022-07-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customertruck_unique_customer_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scanned', 'Scanned'), ('Rejected', 'Rejected')], default='Pending', max_length=25),
        ),
    ]
