# Generated by Django 3.2.13 on 2022-08-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20220731_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scanned', 'Scanned'), ('Rejected', 'Rejected'), ('Safety', 'Safety'), ('Lab', 'Lab'), ('Labresults', 'Labresults'), ('Loading', 'Loading'), ('Loaded', 'Loaded'), ('Released', 'Released'), ('Closed', 'Closed')], default='Pending', max_length=25),
        ),
    ]
