# Generated by Django 3.2.13 on 2022-07-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('coid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.order')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('coid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.order')),
                ('scanned_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.scannedorders')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField()),
                ('q2', models.BooleanField()),
                ('q3', models.BooleanField()),
                ('coid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.order')),
            ],
        ),
        migrations.CreateModel(
            name='Labinspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField(null=True)),
                ('oxygen', models.FloatField(null=True)),
                ('nitrogen', models.FloatField(null=True)),
                ('methane', models.FloatField(null=True)),
                ('coid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.order')),
            ],
        ),
    ]
