# Generated by Django 3.2.13 on 2022-07-31 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20220731_1721'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.order')),
            ],
        ),
        migrations.RenameField(
            model_name='safetychecklist',
            old_name='coid',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='safetyinspection',
            old_name='coid',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='safetyinspection',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='safetyinspection',
            name='scanned_at',
        ),
        migrations.AddField(
            model_name='labinspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safetychecklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safetyinspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safetyinspection',
            name='q1',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safetyinspection',
            name='q2',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safetyinspection',
            name='q3',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ScannedOrders',
        ),
    ]
