# Generated by Django 3.2.13 on 2022-07-31 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20220731_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyChecklistQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_desc', models.CharField(max_length=255)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='labinspection',
            old_name='coid',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='safetychecklist',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='safetychecklist',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='safetychecklist',
            name='q3',
        ),
        migrations.AddField(
            model_name='safetychecklist',
            name='checklist_choice',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SafetyInspection',
        ),
        migrations.AddField(
            model_name='safetychecklist',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operations.safetychecklistquestion'),
            preserve_default=False,
        ),
    ]
