# Generated by Django 3.2.13 on 2022-08-17 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_labresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresults',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labresults',
            name='seal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresults',
            name='vent',
            field=models.BooleanField(default=False),
        ),
    ]
